In [217]:
# Dependencies
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import requests
import censusdata
import re
import geopandas

In [218]:
#Define Funtions

#Funcion For NonDigit Removing Characters from Row
def remove_chars(s):
    clean = int(re.sub('[^0-9]+', '', str(s))[-11:])
    return clean

#Function to get census data according to requirements
def getcensustables(table):
    tablename = 'data_' + table
    print(tablename)
    
    # Set requirements to pull from Census API
    
    variablestopull = allvariablescsv.loc[allvariablescsv['Group']==table]['Name'].tolist()

    print(len(variablestopull))
    
    #variablestopull = variables['Name'].tolist()

    #variablestopull = variables['Name'].tolist()
    listofcounties = ['121', '089']
    yearstopull = range(2012,2018,1)

    #Pull Census Data according to requirement above
    atlantadata = pd.DataFrame()

    for year in yearstopull:
        for county in listofcounties:

            newdata = censusdata.download('acs5', year, censusdata.censusgeo([('state', '13'), ('county', county), ('tract', '*')]),variablestopull)
            type(newdata)
            newdata['YEAR'] = year
            atlantadata = atlantadata.append(newdata)

    #Rename Column Headings from Code to Text
    for variable in variablestopull:
        #print(variable)
        renamevar1 = allvariablescsv.loc[allvariablescsv['Name']==variable]['Label'].iloc[0]
        renamevar2 = allvariablescsv.loc[allvariablescsv['Name']==variable]['Concept'].iloc[0]
        renamevar = renamevar2 + '_'+ renamevar1
        #print(renamevar)
        atlantadata = atlantadata.rename(columns={variable: renamevar})

    #Transform Index to create GeoID


    #Create GeoID Column
    atlantadata['Name2'] = atlantadata.index
    atlantadata['GEOID'] = atlantadata['Name2'].apply(remove_chars)
    atlantadata.drop(columns=['Name2'], inplace=True)
    
    #Only Keep Atlanta Census Tracts(Geocodes)
    finaldata = atlantageocodes.merge(atlantadata, how='left', on='GEOID')
    
    finaldata = finaldata.dropna(axis=0, how='any')
    
    return finaldata

In [254]:
#Code Begins here

#Tables to Load
tablestoloadcsv = pd.read_csv('data/tablestopull.csv')
tablestoload = tablestoloadcsv['Tables'].tolist()

tablestoload = ['B25122','B25061','B25056']

#Allvariables Table
allvariablescsv = pd.read_csv('data/allvariables.csv')

#Atlanta Geo Codes Table
atlantageocodes = pd.read_csv('data/atlantageocodes.csv')

#Create dictionary with each cleaned table as an entry
alltables = dict()  

for table in tablestoload:
    data = getcensustables(table)
    alltables[table] = data
    
    data.to_csv('data/' + table + '.csv')

data_B25122
49
data_B25061
22
data_B25056
24

In [116]:
#Example Usage of Occupancy Over Time

occupancytable = alltables['B25002','B25061','B25056']

occupancytable = occupancytable.groupby('YEAR').sum()
occupancytable['Percent_Occupied'] = (occupancytable['OCCUPANCY STATUS_Estimate!!Total!!Occupied'] / occupancytable['OCCUPANCY STATUS_Estimate!!Total'])*100 

#print(occupancytable.head())

occupancytable = occupancytable.reset_index()


plt.plot(occupancytable['YEAR'], occupancytable['Percent_Occupied'])
plt.title("Occupancy Over Time", fontsize=18)
plt.xlabel("Years", fontsize=18)
plt.ylabel("Occupancy %", fontsize=18)

KeyError: 'B25002'

In [ ]:
occupancytable = alltables['B25002']

occupancytable['Percent_Occupied'] = (occupancytable['OCCUPANCY STATUS_Estimate!!Total!!Occupied'] / occupancytable['OCCUPANCY STATUS_Estimate!!Total'])*100 


geotable = geopandas.read_file('tractdata/tl_2018_13_tract.shp')
#geotable = geotable.astype('int64').dtypes
geotable[['GEOID']] = geotable[['GEOID']].astype('int64')

geotable2 = atlantageocodes.merge(geotable, how='left', on='GEOID')

geotable2 = geotable.set_index('GEOID').join(occupancytable.set_index('GEOID'))

geotable2 = geotable2.dropna(axis=0, how='any')

geotable2.head()

# set a variable that will call whatever column we want to visualise on the map
variable = 'Percent_Occupied'
# set the range for the choropleth
vmin, vmax = 120, 220
# create figure and axes for Matplotlib
fig, ax = plt.subplots(1, figsize=(10, 10))

# create map
geotable2.plot(column=variable, cmap='Blues', linewidth=0.8, ax=ax, edgecolor='0.8')

plt.title("Occupancy Rate By Area", fontsize=18)

In [252]:
occupancytable = alltables['B25002']

occupancytable['Percent_Occupied'] = (occupancytable['OCCUPANCY STATUS_Estimate!!Total!!Occupied'] / occupancytable['OCCUPANCY STATUS_Estimate!!Total'])*100 


geotable = geopandas.read_file('tractdata/tl_2018_13_tract.shp')
#geotable = geotable.astype('int64').dtypes
geotable[['GEOID']] = geotable[['GEOID']].astype('int64')

geotable2 = atlantageocodes.merge(geotable, how='left', on='GEOID')

geotable2 = geotable.set_index('GEOID').join(occupancytable.set_index('GEOID'))

geotable2 = geotable2.dropna(axis=0, how='any')

geotable2.head()

# set a variable that will call whatever column we want to visualise on the map
variable = 'Percent_Occupied'
# set the range for the choropleth
vmin, vmax = 120, 220
# create figure and axes for Matplotlib
fig, ax = plt.subplots(1, figsize=(10, 10))

# create map
geotable2.plot(column=variable, cmap='Blues', linewidth=0.8, ax=ax, edgecolor='0.8')

plt.title("Occupancy Rate By Area", fontsize=18)

KeyError: 'B25002'

In [184]:
#Example Usage of Occupancy Over Time

hhbyincome = alltables['B25122']

hhbyincome = hhbyincome.groupby('YEAR').sum()
#occupancytable['Percent_Occupied'] = (occupancytable['OCCUPANCY STATUS_Estimate!!Total!!Occupied'] / occupancytable['OCCUPANCY STATUS_Estimate!!Total'])*100 

display(hhbyincome.head())

# occupancytable = occupancytable.reset_index()


# plt.plot(occupancytable['YEAR'], occupancytable['Percent_Occupied'])
# plt.title("Occupancy Over Time", fontsize=18)
# plt.xlabel("Years", fontsize=18)
# plt.ylabel("Occupancy %", fontsize=18)

,GEOID,HOUSEHOLD INCOME IN THE PAST 12 MONTHS (IN 2016 INFLATION-ADJUSTED DOLLARS) BY GROSS RENT_Estimate!!Total,"HOUSEHOLD INCOME IN THE PAST 12 MONTHS (IN 2016 INFLATION-ADJUSTED DOLLARS) BY GROSS RENT_Estimate!!Total!!Household income in the past 12 months (in 2016 inflation-adjusted dollars)!!Less than $10,000","HOUSEHOLD INCOME IN THE PAST 12 MONTHS (IN 2016 INFLATION-ADJUSTED DOLLARS) BY GROSS RENT_Estimate!!Total!!Household income in the past 12 months (in 2016 inflation-adjusted dollars)!!Less than $10,000!!With cash rent","HOUSEHOLD INCOME IN THE PAST 12 MONTHS (IN 2016 INFLATION-ADJUSTED DOLLARS) BY GROSS RENT_Estimate!!Total!!Household income in the past 12 months (in 2016 inflation-adjusted dollars)!!Less than $10,000!!With cash rent!!Less than $100","HOUSEHOLD INCOME IN THE PAST 12 MONTHS (IN 2016 INFLATION-ADJUSTED DOLLARS) BY GROSS RENT_Estimate!!Total!!Household income in the past 12 months (in 2016 inflation-adjusted dollars)!!Less than $10,000!!With cash rent!!$100 to $199","HOUSEHOLD INCOME IN THE PAST 12 MONTHS (IN 2016 INFLATION-ADJUSTED DOLLARS) BY GROSS RENT_Estimate!!Total!!Household income in the past 12 months (in 2016 inflation-adjusted dollars)!!Less than $10,000!!With cash rent!!$200 to $299","HOUSEHOLD INCOME IN THE PAST 12 MONTHS (IN 2016 INFLATION-ADJUSTED DOLLARS) BY GROSS RENT_Estimate!!Total!!Household income in the past 12 months (in 2016 inflation-adjusted dollars)!!Less than $10,000!!With cash rent!!$300 to $399","HOUSEHOLD INCOME IN THE PAST 12 MONTHS (IN 2016 INFLATION-ADJUSTED DOLLARS) BY GROSS RENT_Estimate!!Total!!Household income in the past 12 months (in 2016 inflation-adjusted dollars)!!Less than $10,000!!With cash rent!!$400 to $499","HOUSEHOLD INCOME IN THE PAST 12 MONTHS (IN 2016 INFLATION-ADJUSTED DOLLARS) BY GROSS RENT_Estimate!!Total!!Household income in the past 12 months (in 2016 inflation-adjusted dollars)!!Less than $10,000!!With cash rent!!$500 to $599",...,"HOUSEHOLD INCOME IN THE PAST 12 MONTHS (IN 2016 INFLATION-ADJUSTED DOLLARS) BY GROSS RENT_Estimate!!Total!!Household income in the past 12 months (in 2016 inflation-adjusted dollars)!!$20,000 to $34,999!!With cash rent!!$400 to $499","HOUSEHOLD INCOME IN THE PAST 12 MONTHS (IN 2016 INFLATION-ADJUSTED DOLLARS) BY GROSS RENT_Estimate!!Total!!Household income in the past 12 months (in 2016 inflation-adjusted dollars)!!$20,000 to $34,999!!With cash rent!!$500 to $599","HOUSEHOLD INCOME IN THE PAST 12 MONTHS (IN 2016 INFLATION-ADJUSTED DOLLARS) BY GROSS RENT_Estimate!!Total!!Household income in the past 12 months (in 2016 inflation-adjusted dollars)!!$20,000 to $34,999!!With cash rent!!$600 to $699","HOUSEHOLD INCOME IN THE PAST 12 MONTHS (IN 2016 INFLATION-ADJUSTED DOLLARS) BY GROSS RENT_Estimate!!Total!!Household income in the past 12 months (in 2016 inflation-adjusted dollars)!!$20,000 to $34,999!!With cash rent!!$700 to $799","HOUSEHOLD INCOME IN THE PAST 12 MONTHS (IN 2016 INFLATION-ADJUSTED DOLLARS) BY GROSS RENT_Estimate!!Total!!Household income in the past 12 months (in 2016 inflation-adjusted dollars)!!$20,000 to $34,999!!With cash rent!!$800 to $899","HOUSEHOLD INCOME IN THE PAST 12 MONTHS (IN 2016 INFLATION-ADJUSTED DOLLARS) BY GROSS RENT_Estimate!!Total!!Household income in the past 12 months (in 2016 inflation-adjusted dollars)!!$20,000 to $34,999!!With cash rent!!$900 to $999","HOUSEHOLD INCOME IN THE PAST 12 MONTHS (IN 2016 INFLATION-ADJUSTED DOLLARS) BY GROSS RENT_Estimate!!Total!!Household income in the past 12 months (in 2016 inflation-adjusted dollars)!!$20,000 to $34,999!!With cash rent!!$1,000 to $1,249","HOUSEHOLD INCOME IN THE PAST 12 MONTHS (IN 2016 INFLATION-ADJUSTED DOLLARS) BY GROSS RENT_Estimate!!Total!!Household income in the past 12 months (in 2016 inflation-adjusted dollars)!!$20,000 to $34,999!!With cash rent!!$1,250 to $1,499","HOUSEHOLD INCOME IN THE PAST 12 MONTHS (IN 2016 INFLATION-ADJUSTED DOLLARS) BY GROSS RENT_Estimate!!Total!!Household income in the past 12 months (in 2016 inflation-adjusted dollars)!!$20,000 to $34,999!!With cash rent!!$1,500 to $1,999","HOUSEHOLD INCOME IN THE PAST 12 MONTHS (IN 2016 INFLATION-ADJUSTED DOLLARS) BY GROSS RENT_Estimate!!Total!!Household income in the past 12 months (in 2016 inflation-adjusted dollars)!!$20,000 to $34,999!!With cash rent!!$2,000 or more"
YEAR,,,,,,,,,,,,,,,,,,,,,
2012.0,1679136954652,96372.0,20146.0,18943.0,426.0,1975.0,2268.0,1059.0,869.0,1360.0,...,510.0,957.0,2076.0,2674.0,2680.0,2527.0,3169.0,1372.0,980.0,172.0
2013.0,1679136954652,98135.0,20157.0,18856.0,444.0,1882.0,2299.0,985.0,800.0,1297.0,...,519.0,877.0,1893.0,2778.0,2743.0,2429.0,3539.0,1281.0,925.0,249.0
2014.0,1679136954652,101646.0,20131.0,18937.0,438.0,1546.0,2112.0,1118.0,804.0,1189.0,...,571.0,831.0,1701.0,2631.0,2694.0,2517.0,3812.0,1423.0,1134.0,330.0
2015.0,1679136954652,104888.0,19679.0,18425.0,419.0,1493.0,2121.0,951.0,793.0,1163.0,...,455.0,849.0,1716.0,2909.0,2736.0,2674.0,3490.0,1409.0,902.0,331.0
2016.0,1679136954652,107962.0,18621.0,17465.0,435.0,1295.0,1933.0,995.0,681.0,984.0,...,389.0,914.0,1749.0,3035.0,2628.0,2559.0,3818.0,1369.0,953.0,361.0

In [185]:


display(hhbyincome.head())

YEAR,2012.0,2013.0,2014.0,2015.0,2016.0,2017.0
GEOID,1.679137e+12,1.679137e+12,1.679137e+12,1.679137e+12,1.679137e+12,1.679137e+12
HOUSEHOLD INCOME IN THE PAST 12 MONTHS (IN 2016 INFLATION-ADJUSTED DOLLARS) BY GROSS RENT_Estimate!!Total,9.637200e+04,9.813500e+04,1.016460e+05,1.048880e+05,1.079620e+05,1.086620e+05
"HOUSEHOLD INCOME IN THE PAST 12 MONTHS (IN 2016 INFLATION-ADJUSTED DOLLARS) BY GROSS RENT_Estimate!!Total!!Household income in the past 12 months (in 2016 inflation-adjusted dollars)!!Less than $10,000",2.014600e+04,2.015700e+04,2.013100e+04,1.967900e+04,1.862100e+04,1.717000e+04
"HOUSEHOLD INCOME IN THE PAST 12 MONTHS (IN 2016 INFLATION-ADJUSTED DOLLARS) BY GROSS RENT_Estimate!!Total!!Household income in the past 12 months (in 2016 inflation-adjusted dollars)!!Less than $10,000!!With cash rent",1.894300e+04,1.885600e+04,1.893700e+04,1.842500e+04,1.746500e+04,1.620000e+04
"HOUSEHOLD INCOME IN THE PAST 12 MONTHS (IN 2016 INFLATION-ADJUSTED DOLLARS) BY GROSS RENT_Estimate!!Total!!Household income in the past 12 months (in 2016 inflation-adjusted dollars)!!Less than $10,000!!With cash rent!!Less than $100",4.260000e+02,4.440000e+02,4.380000e+02,4.190000e+02,4.350000e+02,3.760000e+02

In [213]:
#Example Usage of Occupancy Over Time

hhbyincome = alltables['B25122']

hhbyincome = hhbyincome.groupby('YEAR').sum()
#occupancytable['Percent_Occupied'] = (occupancytable['OCCUPANCY STATUS_Estimate!!Total!!Occupied'] / occupancytable['OCCUPANCY STATUS_Estimate!!Total'])*100 

#display(hhbyincome.head())

hhbyincome = hhbyincome.transpose()



#hhbyincome = hhbyincome.filter([1,2])

#hhbyincome = hhbyincome[2012.0]

hhbyincome['YEAR'] = hhbyincome.index

#display(hhbyincome)

split1 = hhbyincome['YEAR'].str.split('(in 2016 inflation-adjusted dollars)', expand=True)

#display(split1)

split2 = split1[2].str.split('!!', expand=True)

#display(split2)

hhbyincome['Income'] = split2[1]
hhbyincome['Rent'] = split2[3]

hhbyincome.drop(columns='YEAR')



hhbyincome = hhbyincome[[2012.0,'Income','Rent']]

#display(hhbyincome)
hhbyincome = hhbyincome.dropna(axis=0, how='any')
#display(hhbyincome)
# display(hhbyincome.pivot(index=hhbyincome['Income'], columns=hhbyincome['Rent Change'], values=hhbyincome[2012.0]))

pd.crosstab(index=hhbyincome.iloc[:,1], columns=hhbyincome.iloc[:,2], 
                  values=hhbyincome.iloc[:,0], aggfunc='sum')

Rent,"$1,000 to $1,249","$1,250 to $1,499","$1,500 to $1,999",$100 to $199,"$2,000 or more",$200 to $299,$300 to $399,$400 to $499,$500 to $599,$600 to $699,$700 to $799,$800 to $899,$900 to $999,Less than $100
Income,,,,,,,,,,,,,,
"$10,000 to $19,999",2021.0,911.0,436.0,634.0,136.0,1501.0,1160.0,989.0,988.0,1340.0,2410.0,1651.0,1330.0,75.0
"$20,000 to $34,999",3169.0,1372.0,980.0,35.0,172.0,406.0,315.0,510.0,957.0,2076.0,2674.0,2680.0,2527.0,41.0
"Less than $10,000",2375.0,1086.0,705.0,1975.0,160.0,2268.0,1059.0,869.0,1360.0,1379.0,1662.0,1808.0,1811.0,426.0

In [256]:
#Example Usage of Occupancy Over Time

contractrent = alltables['B25056']

contractrent = contractrent.groupby('YEAR').sum()
#occupancytable['Percent_Occupied'] = (occupancytable['OCCUPANCY STATUS_Estimate!!Total!!Occupied'] / occupancytable['OCCUPANCY STATUS_Estimate!!Total'])*100 

#display(hhbyincome.head())

contractrent = contractrent.transpose()



#hhbyincome = hhbyincome.filter([1,2])

#hhbyincome = hhbyincome[2012.0]

contractrent['YEAR'] = contractrent.index

#display(hhbyincome)

split1 = contractrent['YEAR'].str.split('Total!!', expand=True)

#display(split1)

#split2 = split1[2].str.split('!!', expand=True)

#display(split2)

#hhbyincome['Income'] = split2[1]
contractrent['Rent'] = split1[1]

#hhbyincome.drop(columns='YEAR')



contractrent = contractrent[[2012.0,'Rent']]

#display(hhbyincome)
#hhbyincome = hhbyincome.dropna(axis=0, how='any')
display(contractrent)
# display(hhbyincome.pivot(index=hhbyincome['Income'], columns=hhbyincome['Rent Change'], values=hhbyincome[2012.0]))

# pd.crosstab(index=contractrent.iloc[:,0], columns=contractrent.iloc[:,1], values=contractrent.iloc[:,1], aggfunc='sum')

# pd.crosstab(index=contractrent.iloc[:,1], columns=contractrent.iloc[:,1], values=contractrent.iloc[:,0], aggfunc='sum')
contractrent.index = contractrent['Rent']
# contractrent.drop(rows=['Rent'])
contractrent.transpose()

YEAR,2012.0,Rent
GEOID,1.679137e+12,None
CONTRACT RENT_Estimate!!Total,9.637200e+04,None
CONTRACT RENT_Estimate!!Total!!With cash rent,9.344400e+04,With cash rent
CONTRACT RENT_Estimate!!Total!!With cash rent!!Less than $100,2.753000e+03,With cash rent!!Less than $100
CONTRACT RENT_Estimate!!Total!!With cash rent!!$100 to $149,1.789000e+03,With cash rent!!$100 to $149
CONTRACT RENT_Estimate!!Total!!With cash rent!!$150 to $199,2.452000e+03,With cash rent!!$150 to $199
CONTRACT RENT_Estimate!!Total!!With cash rent!!$200 to $249,2.273000e+03,With cash rent!!$200 to $249
CONTRACT RENT_Estimate!!Total!!With cash rent!!$250 to $299,1.436000e+03,With cash rent!!$250 to $299
CONTRACT RENT_Estimate!!Total!!With cash rent!!$300 to $349,1.369000e+03,With cash rent!!$300 to $349
CONTRACT RENT_Estimate!!Total!!With cash rent!!$350 to $399,1.394000e+03,With cash rent!!$350 to $399
CONTRACT RENT_Estimate!!Total!!With cash rent!!$400 to $449,2.077000e+03,With cash rent!!$400 to $449
CONTRACT RENT_Estimate!!Total!!With cash rent!!$450 to $499,2.724000e+03,With cash rent!!$450 to $499
CONTRACT RENT_Estimate!!Total!!With cash rent!!$500 to $549,4.523000e+03,With cash rent!!$500 to $549
CONTRACT RENT_Estimate!!Total!!With cash rent!!$550 to $599,4.178000e+03,With cash rent!!$550 to $599
CONTRACT RENT_Estimate!!Total!!With cash rent!!$600 to $649,5.529000e+03,With cash rent!!$600 to $649
CONTRACT RENT_Estimate!!Total!!With cash rent!!$650 to $699,5.677000e+03,With cash rent!!$650 to $699
CONTRACT RENT_Estimate!!Total!!With cash rent!!$700 to $749,5.567000e+03,With cash rent!!$700 to $749
CONTRACT RENT_Estimate!!Total!!With cash rent!!$750 to $799,4.765000e+03,With cash rent!!$750 to $799
CONTRACT RENT_Estimate!!Total!!With cash rent!!$800 to $899,1.115100e+04,With cash rent!!$800 to $899
CONTRACT RENT_Estimate!!Total!!With cash rent!!$900 to $999,8.720000e+03,With cash rent!!$900 to $999
"CONTRACT RENT_Estimate!!Total!!With cash rent!!$1,000 to $1,249",1.175700e+04,"With cash rent!!$1,000 to $1,249"
"CONTRACT RENT_Estimate!!Total!!With cash rent!!$1,250 to $1,499",7.020000e+03,"With cash rent!!$1,250 to $1,499"
"CONTRACT RENT_Estimate!!Total!!With cash rent!!$1,500 to $1,999",4.189000e+03,"With cash rent!!$1,500 to $1,999"
"CONTRACT RENT_Estimate!!Total!!With cash rent!!$2,000 to $2,499",2.101000e+03,"With cash rent!!$2,000 to $2,499"
"CONTRACT RENT_Estimate!!Total!!With cash rent!!$2,500 to $2,999",2.928000e+03,"With cash rent!!$2,500 to $2,999"

Rent,None,None,With cash rent,With cash rent!!Less than $100,With cash rent!!$100 to $149,With cash rent!!$150 to $199,With cash rent!!$200 to $249,With cash rent!!$250 to $299,With cash rent!!$300 to $349,With cash rent!!$350 to $399,...,With cash rent!!$650 to $699,With cash rent!!$700 to $749,With cash rent!!$750 to $799,With cash rent!!$800 to $899,With cash rent!!$900 to $999,"With cash rent!!$1,000 to $1,249","With cash rent!!$1,250 to $1,499","With cash rent!!$1,500 to $1,999","With cash rent!!$2,000 to $2,499","With cash rent!!$2,500 to $2,999"
YEAR,,,,,,,,,,,,,,,,,,,,,
2012.0,1.67914e+12,96372,93444,2753,1789,2452,2273,1436,1369,1394,...,5677,5567,4765,11151,8720,11757,7020,4189,2101,2928
Rent,None,None,With cash rent,With cash rent!!Less than $100,With cash rent!!$100 to $149,With cash rent!!$150 to $199,With cash rent!!$200 to $249,With cash rent!!$250 to $299,With cash rent!!$300 to $349,With cash rent!!$350 to $399,...,With cash rent!!$650 to $699,With cash rent!!$700 to $749,With cash rent!!$750 to $799,With cash rent!!$800 to $899,With cash rent!!$900 to $999,"With cash rent!!$1,000 to $1,249","With cash rent!!$1,250 to $1,499","With cash rent!!$1,500 to $1,999","With cash rent!!$2,000 to $2,499","With cash rent!!$2,500 to $2,999"

In [257]:
#Example Usage of Occupancy Over Time

availability = alltables['B25061']

availability = availability.groupby('YEAR').sum()
#occupancytable['Percent_Occupied'] = (occupancytable['OCCUPANCY STATUS_Estimate!!Total!!Occupied'] / occupancytable['OCCUPANCY STATUS_Estimate!!Total'])*100 

#display(hhbyincome.head())

availability = availability.transpose()



#hhbyincome = hhbyincome.filter([1,2])

#hhbyincome = hhbyincome[2012.0]

availability['YEAR'] = availability.index

#display(hhbyincome)

split1 = availability['YEAR'].str.split('Total!!', expand=True)

#display(split1)

#split2 = split1[2].str.split('!!', expand=True)

#display(split2)

#hhbyincome['Income'] = split2[1]
availability['Rent'] = split1[1]

#hhbyincome.drop(columns='YEAR')



availability = availability[[2012.0,'Rent']]

#display(hhbyincome)
#hhbyincome = hhbyincome.dropna(axis=0, how='any')
display(availability)
# display(hhbyincome.pivot(index=hhbyincome['Income'], columns=hhbyincome['Rent Change'], values=hhbyincome[2012.0]))

# pd.crosstab(index=availability.iloc[:,0], columns=availability.iloc[:,1], values=availability.iloc[:,1], aggfunc='sum')

# pd.crosstab(index=availability.iloc[:,1], columns=availability.iloc[:,1], values=availability.iloc[:,0], aggfunc='sum')
availability.index = availability['Rent']
# availability.drop(rows=['Rent'])
availability.transpose()

YEAR                                                2012.0              Rent
GEOID                                         1.679137e+12              None
RENT ASKED_Estimate!!Total                    1.622400e+04              None
RENT ASKED_Estimate!!Total!!Less than $100    1.440000e+02    Less than $100
RENT ASKED_Estimate!!Total!!$100 to $149      9.100000e+01      $100 to $149
RENT ASKED_Estimate!!Total!!$150 to $199      1.070000e+02      $150 to $199
RENT ASKED_Estimate!!Total!!$200 to $249      1.040000e+02      $200 to $249
RENT ASKED_Estimate!!Total!!$250 to $299      1.040000e+02      $250 to $299
RENT ASKED_Estimate!!Total!!$300 to $349      4.200000e+01      $300 to $349
RENT ASKED_Estimate!!Total!!$350 to $399      9.500000e+01      $350 to $399
RENT ASKED_Estimate!!Total!!$400 to $449      2.960000e+02      $400 to $449
RENT ASKED_Estimate!!Total!!$450 to $499      4.320000e+02      $450 to $499
RENT ASKED_Estimate!!Total!!$500 to $549      1.207000e+03      $500 to $549
RENT ASKED_Estimate!!Total!!$550 to $599      1.499000e+03      $550 to $599
RENT ASKED_Estimate!!Total!!$600 to $649      9.750000e+02      $600 to $649
RENT ASKED_Estimate!!Total!!$650 to $699      1.265000e+03      $650 to $699
RENT ASKED_Estimate!!Total!!$700 to $749      1.071000e+03      $700 to $749
RENT ASKED_Estimate!!Total!!$750 to $799      6.290000e+02      $750 to $799
RENT ASKED_Estimate!!Total!!$800 to $899      2.131000e+03      $800 to $899
RENT ASKED_Estimate!!Total!!$900 to $999      1.393000e+03      $900 to $999
RENT ASKED_Estimate!!Total!!$1,000 to $1,249  2.354000e+03  $1,000 to $1,249
RENT ASKED_Estimate!!Total!!$1,250 to $1,499  1.193000e+03  $1,250 to $1,499
RENT ASKED_Estimate!!Total!!$1,500 to $1,999  5.790000e+02  $1,500 to $1,999
RENT ASKED_Estimate!!Total!!$2,000 to $2,499  5.130000e+02  $2,000 to $2,499

Rent,None,None,Less than $100,$100 to $149,$150 to $199,$200 to $249,$250 to $299,$300 to $349,$350 to $399,$400 to $449,...,$600 to $649,$650 to $699,$700 to $749,$750 to $799,$800 to $899,$900 to $999,"$1,000 to $1,249","$1,250 to $1,499","$1,500 to $1,999","$2,000 to $2,499"
YEAR,,,,,,,,,,,,,,,,,,,,,
2012.0,1.67914e+12,16224,144,91,107,104,104,42,95,296,...,975,1265,1071,629,2131,1393,2354,1193,579,513
Rent,None,None,Less than $100,$100 to $149,$150 to $199,$200 to $249,$250 to $299,$300 to $349,$350 to $399,$400 to $449,...,$600 to $649,$650 to $699,$700 to $749,$750 to $799,$800 to $899,$900 to $999,"$1,000 to $1,249","$1,250 to $1,499","$1,500 to $1,999","$2,000 to $2,499"